services:
  db:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: website_data
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build: ./backend  
    image: water-tracker
    container_name: app-container
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/website_data
    ports:
      - "8000:8000"
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge

