version: "3.8"
services:
  db:
    image: postgres:latest 
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres  
      POSTGRES_PASSWORD: postgres  
      POSTGRES_DB: website_data  
    ports:
      - "5432:5432"  
    volumes:
      - postgres-data:/var/lib/postgresql/data  

  app:
    image: your-app-image  # Replace with application container image
    container_name: app-container
    depends_on:
      - db  
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/website_data  
    ports:
      - "8080:8080"  

volumes:
  postgres-data:
